### ISSUE TITLE
Followed SubDAOs should only show up once.

### ISSUE THREAD

**Issue by elsehow** [DA0-DA0/dao-dao-ui#1223]
![image](https://user-images.githubusercontent.com/7132461/230226996-06ac1b31-a26f-432d-bcf3-a1ee1853e7df.png)

People will often follow SubDAOs. That leads to a situation where SubDAOs show up twice in the sidebar (shown above).

SubDAOs you're following should only show up once. 

My suggestion:

- If you follow a SubDAO and its parent DAO, place a ["following" icon](https://thenounproject.com/browse/icons/term/following/) next to SubDAOs you follow.

- If you follow a SubDAO and *not* its parent, show the SubDAO with a "following" icon next to it, and *only* the top-level DAO as its parent (but no sibling DAOs).

Curious to hear any other suggestions to deal with this situation.

**Comment by Trigs-0** [comment]
I've been wondering about the likelihood of someone following a subDAO and not the parent.

But I like the idea of having an indicator on if you're following the subDAO or not, instead of duplicating the subDAO in your following list.

I also like the idea of showing the parent DAO but not the sibling DAOs if you don't follow the parent.

Maybe they could be slightly faded if you don't follow them, but an indicator could work too.

It would also be nice if they defaulted to collapsed. Maybe it defaults to collapsed, but still shows the subDAOs you follow as a partially expanded list. Then you can pop it open to see the subDAOs you don't follow, or fully collapse it to show no subDAOs as an option.

**Comment by NoahSaso** [comment]
> I've been wondering about the likelihood of someone following a subDAO and not the parent.
> 
> But I like the idea of having an indicator on if you're following the subDAO or not, instead of duplicating the subDAO in your following list.
> 
> I also like the idea of showing the parent DAO but not the sibling DAOs if you don't follow the parent.
> 
> Maybe they could be slightly faded if you don't follow them, but an indicator could work too.
> 
> It would also be nice if they defaulted to collapsed. Maybe it defaults to collapsed, but still shows the subDAOs you follow as a partially expanded list. Then you can pop it open to see the subDAOs you don't follow, or fully collapse it to show no subDAOs as an option.

these are great thoughts! i'm thinking maybe we just shouldn't ever show SubDAOs unless they're followed. it's kind of a mess. really there should be no DAOs visible that you didn't choose to follow.

what if instead we show all the DAOs you're following, with no SubDAOs. if you follow both a parent and its SubDAO, we nest the SubDAO under its parent only. that's it. thoughts?

cc @elsehow

**Comment by Trigs-0** [comment]
That sounds perfect, actually. Well done!👏
