### ISSUE TITLE
Bug: Create DAO action as a DAO proposal

### ISSUE THREAD

**Issue by kopeboy** [DA0-DA0/dao-dao-ui#1784]
If you try to do it from a DAO, ie. as a proposal, the action is blank and not usable.

![image](https://github.com/DA0-DA0/dao-dao-ui/assets/4728367/51b69937-1a1c-451a-a4df-59f59153c0b9)

This, together with [this other bug](https://github.com/DA0-DA0/dao-dao-ui/issues/1785) I just posted makes it impossible to create actual SubDAOs (that have a different admin) from the UI.

Users may think that doing a "Recognize SubDAO" proposal from the "Admin" is enough, but that's not the case, cause the `admin` address must be set on the SubDAO of course!

**Comment by NoahSaso** [comment]
ah, the actual bug here is that you're not supposed to be able to use the "Create DAO" action manually, and the search bar in the action library is accidentally revealing hidden actions. that action is just used for rendering when chain governance proposals create DAOs (on Kujira this is the only way to create a DAO right now). for SubDAOs, you're supposed to use the SubDAO creation interface only. and the admin bug is now fixed :)

thanks for finding these!!

**Comment by noahsaso** [comment]
ah, the actual bug here is that you're not supposed to be able to use the "Create DAO" action manually, and the search bar in the action library is accidentally revealing hidden actions. that action is just used for rendering when chain governance proposals create DAOs (on Kujira this is the only way to create a DAO right now). for SubDAOs, you're supposed to use the SubDAO creation interface only. and the admin bug is now fixed :)

thanks for finding these!!
