### ISSUE TITLE
Add support for Active Threshold option in token based DAOs

### ISSUE THREAD

**Issue by JakeHartnell** [DA0-DA0/dao-dao-ui#801]
Should default to something sensible like 10%.

Otherwise, there is a race to stake scenario.

**Comment by ezekiiel** [comment]
Some context:

When you create a DAO, the first person to stake in the DAO "controls" it. For example, if I made a DAO with ten dollars in it, the first person to stake in that DAO could make and execute a proposal to send themselves the money. This is because if they are the first person to stake, there is a period of time wherein they have 100% [voting power](https://github.com/DA0-DA0/dao-contracts/wiki/A-brief-overview-of-DAO-DAO-voting#staking) (they are the only staker).

To get around this, DAOs can optionally set an [active threshold](https://github.com/DA0-DA0/dao-contracts/blob/78b9f7a300ccda63b40db8396d173002cbd23ac8/contracts/cw20-staked-balance-voting/src/msg.rs#L44-L55) which sets the percent of all tokens that must be staked for the DAO to be active. For the DAO DAO DAO, we set this to 4% so that half of the contributor drop needed to be staked before the DAO would spin up.

We do not currently have UI for this! but it shouldn't be too bad to add. This should likely be disabled and then default to a quite low value when enabled. We may want to set the default value as some percentage of the tokens that are not going to the treasury.

If you're not familiar with converting message types from contracts to the kind of stuff you use in the frontend, see [here](https://docs.daodao.zone/docs/recipes/executing-smart-contracts#json-conversion) for some docs on JSON conversion.
