### ISSUE TITLE
Combine related actions

### ISSUE THREAD

**Issue by JakeHartnell** [DA0-DA0/dao-dao-ui#943]
The list of actions that is growing! As a result it's nice to combine related actions when possible.

A few that can be combined:
- "Display NFT Collection in Treasury" and "Remove NFT Collection from Treasury" -> Manage Treasury NFT Collections
- "Display Token Balance in Treasury" and "Remove Token Balance from Treasury" -> Manage Treasury Tokens
- "Set Item" and "Remove Item"

**Comment by elsehow** [comment]
What do we imagine it looks like to combine actions? Is it (1) to create a single action that has multiple tabs? Or is it (2) to create a "MetaAction" (or perhaps ActionPack) that contains multiple actions?

The difference between these two is that in (1) the action designer has to build more UI - they have to build UI to switch between different actions. I can imagine this getting chaotic. People might try to squeeze too much into a tab interface.

In (2), we can provide the UI for switching between actions - they just need to expose something generic (like a name for the action and a description). Then we can design some interface for selecting the specific action from the pack. So I prefer (2).

What do others think? Am I making this too complicated?

By the way, I think the actions we have should be combined even more radically. I think we could have a "Manage membership & voting" Action Pack that wraps together a lot of the actions we have today.

**Comment by JakeHartnell** [comment]
1 is easier in the short term, but 2 is probably a better solution. Though it will need some design.

If someone has a design ready let's go for it. Otherwise, we can ship the simple thing for now and think about the long term solution here.

**Comment by elsehow** [comment]
Did someone call for a terribly rendered lo-fi design? Here it is:

![Notebook 5 - page 1](https://user-images.githubusercontent.com/7132461/206261380-1501d0e1-5d3b-4fbf-80bf-a9231176fa7b.png)

This lo-fi mockup describes a hypothetical "Configure your DAO" Action Pack.

My design has two main components:

- First, there is an interface that describes all of the actions in the action pack (top). These names (and perhaps some emojis, descriptions, tooltips) might be described by a Manifest inside the Action Pack.
- Second, there is an interface that shows individual Action components (bottom). Note the breadcrumb interface at the top of that component, which would allow you to navigate back to all of the Action Pack's actions. This is important for letting the user explore different actions in the pack.

Another thought occurred to me here: we'll probably want Action Packs to bundle their own i18n. Again, there are tradeoffs here. On the downside, it may make it so that Actions aren't translated into all of the languages supported by the frontend.  On the upside, it allows action designers not to have to merge a PR with us just to get their thing localized. It also prevents i18n pollution, where an increasing number of actions increase the weight of each translation.

@NoahSaso Do you have any thoughts on this? I agree broadly with Jake's assessment of (1) and (2), but the relative ease is really up to you. What would you prefer to do?

**Comment by JakeHartnell** [comment]
> Another thought occurred to me here: we'll probably want Action Packs to bundle their own i18n. Again, there are tradeoffs here. On the downside, it may make it so that Actions aren't translated into all of the languages supported by the frontend. On the upside, it allows action designers not to have to merge a PR with us just to get their thing localized. It also prevents i18n pollution, where an increasing number of actions increase the weight of each translation.

**Comment by elsehow** [comment]
Sounds good to me. Let's keep this thread open for a v2.1 release that includes Action Packs.
